<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class CodesResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'ean13' => 'string',
      'ean8' => 'string'
  );

  static $attributeMap = array(
      'ean13' => 'ean13',
      'ean8' => 'ean8'
  );

  
  /**
  * ean13 код билета
  */
  public $ean13; /* string */
  /**
  * ean13 код билета
  */
  public $ean8; /* string */

  public function __construct(array $data = null) {
    
    if(isset($data["ean13"])) {
      $this->ean13 = $data["ean13"];
    }
    
    
    if(isset($data["ean8"])) {
      $this->ean8 = $data["ean8"];
    }
    
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
