<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class EditEvent implements ArrayAccess {
    static $swaggerTypes = array(
        'ticket_types' => 'TicketTypeIncludeApiRequest[]',
        'name' => 'string',
        'description_short' => 'string',
        'description_html' => 'string',
        'starts_at' => 'string',
        'ends_at' => 'string',
        'categories' => 'CategoryInclude[]',
        'location' => 'LocationInclude',
        'poster_image_url' => 'string',
        'properties' => 'string[]',
        'custom' => 'object',
        'questions' => 'QuestionInclude[]',
        'access_status' => 'string'
    );

    static $attributeMap = array(
        'ticket_types' => 'ticket_types',
        'name' => 'name',
        'description_short' => 'description_short',
        'description_html' => 'description_html',
        'starts_at' => 'starts_at',
        'ends_at' => 'ends_at',
        'categories' => 'categories',
        'location' => 'location',
        'poster_image_url' => 'poster_image_url',
        'properties' => 'properties',
        'custom' => 'custom',
        'questions' => 'questions',
        'access_status' => 'access_status'
    );

    
    /**
    * Список видов билетов
    *
    * @var TicketTypeIncludeApiRequest[]
    */
    public $ticket_types;
    /**
    * Название события
    *
    * @var string
    */
    public $name;
    /**
    * Краткое описание/подзаголовок события
    *
    * @var string
    */
    public $description_short;
    /**
    * Полное описание с html-тегами
    *
    * @var string
    */
    public $description_html;
    /**
    * Дата начала события в формате ISO
    *
    * @var string
    */
    public $starts_at;
    /**
    * Дата окончания события в формате ISO
    *
    * @var string
    */
    public $ends_at;
    /**
    * Список категорий, в которые входит событие
    *
    * @var CategoryInclude[]
    */
    public $categories;
    /**
    * Место проведения события
    *
    * @var LocationInclude
    */
    public $location;
    /**
    * URL картинки события
    *
    * @var string
    */
    public $poster_image_url;
    /**
    * Список настроек события (например, мультианкета)
    *
    * @var string[]
    */
    public $properties;
    /**
    * Объект с дополнительными полями, специфичными для данной организации
    *
    * @var object
    */
    public $custom;
    /**
    * Список вопросов в анкете регистрации
    *
    * @var QuestionInclude[]
    */
    public $questions;
    /**
    * Статус доступа к событию
    *
    * @var string
    */
    public $access_status;

    public function __construct(array $data = null) {
    
        if(isset($data["ticket_types"])) {
            $this->ticket_types = $data["ticket_types"];
        }
    
    
        if(isset($data["name"])) {
            $this->name = $data["name"];
        }
    
    
        if(isset($data["description_short"])) {
            $this->description_short = $data["description_short"];
        }
    
    
        if(isset($data["description_html"])) {
            $this->description_html = $data["description_html"];
        }
    
    
        if(isset($data["starts_at"])) {
            $this->starts_at = $data["starts_at"];
        }
    
    
        if(isset($data["ends_at"])) {
            $this->ends_at = $data["ends_at"];
        }
    
    
        if(isset($data["categories"])) {
            $this->categories = $data["categories"];
        }
    
    
        if(isset($data["location"])) {
            $this->location = $data["location"];
        }
    
    
        if(isset($data["poster_image_url"])) {
            $this->poster_image_url = $data["poster_image_url"];
        }
    
    
        if(isset($data["properties"])) {
            $this->properties = $data["properties"];
        }
    
    
        if(isset($data["custom"])) {
            $this->custom = $data["custom"];
        }
    
    
        if(isset($data["questions"])) {
            $this->questions = $data["questions"];
        }
    
    
        if(isset($data["access_status"])) {
            $this->access_status = $data["access_status"];
        }
    
    }

    public function offsetExists($offset) {
        return isset($this->$offset);
    }

    public function offsetGet($offset) {
        return $this->$offset;
    }

    public function offsetSet($offset, $value) {
        $this->$offset = $value;
    }

    public function offsetUnset($offset) {
        unset($this->$offset);
    }
}
