<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class PaymentResponse implements ArrayAccess {
    static $swaggerTypes = array(
        'amount' => 'float',
        'paid_at' => 'DateTime',
        'payment_type' => 'string'
    );

    static $attributeMap = array(
        'amount' => 'amount',
        'paid_at' => 'paid_at',
        'payment_type' => 'payment_type'
    );

    
    /**
    * Оплаченная сумма (количество рублей, отданных покупателем платёжной системе в этом заказе)
    *
    * @var float
    */
    public $amount;
    /**
    * Дата оплаты
    *
    * @var DateTime
    */
    public $paid_at;
    /**
    * Платёжная система оплаты
    *
    * @var string
    */
    public $payment_type;

    public function __construct(array $data = null) {
    
        if(isset($data["amount"])) {
            $this->amount = $data["amount"];
        }
    
    
        if(isset($data["paid_at"])) {
            $this->paid_at = $data["paid_at"];
        }
    
    
        if(isset($data["payment_type"])) {
            $this->payment_type = $data["payment_type"];
        }
    
    }

    public function offsetExists($offset) {
        return isset($this->$offset);
    }

    public function offsetGet($offset) {
        return $this->$offset;
    }

    public function offsetSet($offset, $value) {
        $this->$offset = $value;
    }

    public function offsetUnset($offset) {
        unset($this->$offset);
    }
}
