<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class QuestionInclude implements ArrayAccess {
  static $swaggerTypes = array(
      'field_id' => 'string',
      'is_mandatory' => 'boolean',
      'name' => 'string',
      'comment' => 'string'
  );

  static $attributeMap = array(
      'field_id' => 'field_id',
      'is_mandatory' => 'is_mandatory',
      'name' => 'name',
      'comment' => 'comment'
  );

  
  /**
  * Текстовый идентификатор для стандартных вопросов
  */
  public $field_id; /* string */
  /**
  * Обязателен ли вопрос:
  */
  public $is_mandatory; /* boolean */
  /**
  * Текст вопроса
  */
  public $name; /* string */
  /**
  * Подсказка под вопросом
  */
  public $comment; /* string */

  public function __construct(array $data = null) {
    $this->field_id = $data["field_id"];
    $this->is_mandatory = $data["is_mandatory"];
    $this->name = $data["name"];
    $this->comment = $data["comment"];
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
