<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class TicketTypeRequest implements ArrayAccess {
    static $swaggerTypes = array(
        'id' => 'int',
        'price' => 'int',
        'status' => 'string',
        'name' => 'string',
        'description' => 'string',
        'sale_starts_at' => 'DateTime',
        'sale_ends_at' => 'DateTime',
        'limit' => 'int'
    );

    static $attributeMap = array(
        'id' => 'id',
        'price' => 'price',
        'status' => 'status',
        'name' => 'name',
        'description' => 'description',
        'sale_starts_at' => 'sale_starts_at',
        'sale_ends_at' => 'sale_ends_at',
        'limit' => 'limit'
    );

    
    /**
    * Номер существующего типа билета
    *
    * @var int
    */
    public $id;
    /**
    * Цена существующего типа билета
    *
    * @var int
    */
    public $price;
    /**
    * Статус типа билета
    *
    * @var string
    */
    public $status;
    /**
    * Название типа билета
    *
    * @var string
    */
    public $name;
    /**
    * Описание типа билета
    *
    * @var string
    */
    public $description;
    /**
    * Дата начала продажи типа билета
    *
    * @var DateTime
    */
    public $sale_starts_at;
    /**
    * Дата окончания продажи типа билета
    *
    * @var DateTime
    */
    public $sale_ends_at;
    /**
    * Ограничение на количество билетов этого типа
    *
    * @var int
    */
    public $limit;

    public function __construct(array $data = null) {
    
        if(isset($data["id"])) {
            $this->id = $data["id"];
        }
    
    
        if(isset($data["price"])) {
            $this->price = $data["price"];
        }
    
    
        if(isset($data["status"])) {
            $this->status = $data["status"];
        }
    
    
        if(isset($data["name"])) {
            $this->name = $data["name"];
        }
    
    
        if(isset($data["description"])) {
            $this->description = $data["description"];
        }
    
    
        if(isset($data["sale_starts_at"])) {
            $this->sale_starts_at = $data["sale_starts_at"];
        }
    
    
        if(isset($data["sale_ends_at"])) {
            $this->sale_ends_at = $data["sale_ends_at"];
        }
    
    
        if(isset($data["limit"])) {
            $this->limit = $data["limit"];
        }
    
    }

    public function offsetExists($offset) {
        return isset($this->$offset);
    }

    public function offsetGet($offset) {
        return $this->$offset;
    }

    public function offsetSet($offset, $value) {
        $this->$offset = $value;
    }

    public function offsetUnset($offset) {
        unset($this->$offset);
    }
}
