<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class TicketResponse implements ArrayAccess {
  static $swaggerTypes = array(
      'id' => 'int',
      'number' => 'string',
      'answers' => 'object',
      'ticket_type' => 'array[TicketTypeResponse]',
      'attendance' => 'array[AttendanceResponse]',
      'place' => 'array[PlaceResponse]',
      'codes' => 'array[CodesResponse]'
  );

  static $attributeMap = array(
      'id' => 'id',
      'number' => 'number',
      'answers' => 'answers',
      'ticket_type' => 'ticket_type',
      'attendance' => 'attendance',
      'place' => 'place',
      'codes' => 'codes'
  );

  
  /**
  * Уникальный номер типа билета
  */
  public $id; /* int */
  /**
  * Номер билета
  */
  public $number; /* string */
  public $answers; /* object */
  public $ticket_type; /* array[TicketTypeResponse] */
  public $attendance; /* array[AttendanceResponse] */
  public $place; /* array[PlaceResponse] */
  public $codes; /* array[CodesResponse] */

  public function __construct(array $data = null) {
    
    if(isset($data["id"])) {
      $this->id = $data["id"];
    }
    
    
    if(isset($data["number"])) {
      $this->number = $data["number"];
    }
    
    
    if(isset($data["answers"])) {
      $this->answers = $data["answers"];
    }
    
    
    if(isset($data["ticket_type"])) {
      $this->ticket_type = $data["ticket_type"];
    }
    
    
    if(isset($data["attendance"])) {
      $this->attendance = $data["attendance"];
    }
    
    
    if(isset($data["place"])) {
      $this->place = $data["place"];
    }
    
    
    if(isset($data["codes"])) {
      $this->codes = $data["codes"];
    }
    
  }

  public function offsetExists($offset) {
    return isset($this->$offset);
  }

  public function offsetGet($offset) {
    return $this->$offset;
  }

  public function offsetSet($offset, $value) {
    $this->$offset = $value;
  }

  public function offsetUnset($offset) {
    unset($this->$offset);
  }
}
