<?php
/**
 *  Copyright 2015 Reverb Technologies, Inc.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

/**
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */

namespace TimepadApi\models;

use \ArrayAccess;

class WebhookApiResponse implements ArrayAccess {
    static $swaggerTypes = array(
        'id' => 'int',
        'organization' => 'int',
        'url' => 'string',
        'type' => 'string',
        'secret' => 'string'
    );

    static $attributeMap = array(
        'id' => 'id',
        'organization' => 'organization',
        'url' => 'url',
        'type' => 'type',
        'secret' => 'secret'
    );

    
    /**
    * Идентификатор webhook'а
    *
    * @var int
    */
    public $id;
    /**
    * Идентификатор организации
    *
    * @var int
    */
    public $organization;
    /**
    * URL-адресс для колбека при событии
    *
    * @var string
    */
    public $url;
    /**
    * Тип webhook'а
    *
    * @var string
    */
    public $type;
    /**
    * Ключ подписи webhook'а
    *
    * @var string
    */
    public $secret;

    public function __construct(array $data = null) {
    
        if(isset($data["id"])) {
            $this->id = $data["id"];
        }
    
    
        if(isset($data["organization"])) {
            $this->organization = $data["organization"];
        }
    
    
        if(isset($data["url"])) {
            $this->url = $data["url"];
        }
    
    
        if(isset($data["type"])) {
            $this->type = $data["type"];
        }
    
    
        if(isset($data["secret"])) {
            $this->secret = $data["secret"];
        }
    
    }

    public function offsetExists($offset) {
        return isset($this->$offset);
    }

    public function offsetGet($offset) {
        return $this->$offset;
    }

    public function offsetSet($offset, $value) {
        $this->$offset = $value;
    }

    public function offsetUnset($offset) {
        unset($this->$offset);
    }
}
